# -*- coding: utf-8 -*-
# :Project:   pymeshfix -- Configuration to build and upload Linux wheels to PyPI
# :Author:    Alex Kaszynski <akascap@gmail.com>
# :License:   MIT License

# borrowed parts from
# https://github.com/python-rapidjson/python-rapidjson/blob/master/.appveyor.yml

# Builds wheels for Linux using cibuildwheel, inside the manylinux1 Docker image.
# builds 64-bit Python2.7, Python3.5, Python3.6, Python3.7

matrix:
  include:
    - sudo: required
      language: python
      python: "3.6"
      services:
        - docker
      env: PIP=pip
    - os: osx
      osx_image: xcode8.3

env:
  global:
    - CIBW_BEFORE_BUILD_LINUX="pip install numpy==1.15.0; pip install cython; yum install libXt -y"
    - CIBW_BEFORE_BUILD_MACOS="pip install numpy==1.15.0; pip install cython"
    - CIBW_TEST_REQUIRES="pytest"
    - CIBW_TEST_COMMAND="pytest {project}/tests/"
    - CIBW_SKIP="cp27-cp27m-manylinux1_x86_64 cp34-* *manylinux1_i686*"
    - TWINE_USERNAME=akaszynski
      # Note: TWINE_PASSWORD is set in Travis settings


before_install:
  # configure a headless display
  - git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
  - source ./gl-ci-helpers/travis/setup_headless_display.sh


install:
  # Setup for python 3 wheels in Mac OS X
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      brew upgrade python
      # CFLAGS='-stdlib=libc++'
    fi;
  - pip3 install --upgrade cibuildwheel
  # for building docs in linux
  - |
    if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      pip3 install -r requirements.txt
    fi;

script:
  - cibuildwheel --output-dir wheelhouse
      # Make documentation
  - |
    if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      cd ./wheelhouse
      pip3 install pymeshfix-*-cp36-cp36m-manylinux1_x86_64.whl
      cd ../docs
      make html
      set -e
      make html
      cd ..
      set +x
    fi;
 # TODO: include `doctr deploy --built-docs ./docs/_build/html/ .;` above
  - if [ "${TRAVIS_TAG:-}" != "" ]; then
      python3 setup.py sdist;
      cp dist/*.tar.gz wheelhouse/;
      pip3 install twine;
      python3 -m twine upload --skip-existing wheelhouse/*;
    fi

notifications:
  email: false
